### ISSUE TITLE
Fix TODO messages in the codebase (and try to use GitHub issues in the future where possible)

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#423]
- [ ] Hardcoding privacy values in posts/editor.js should maybe be done by gon instead? (keep them hardcoded in just one location)
- [ ] The Javascript has a lot of hacks or at least a lot of things labeled as such; see if we can unhackify these or at least test them to make sure they work exactly as expected
- [ ] users/new.js doesn't validateUsername false when the POST to /users/username fails (the callback is a separate scope)
- [ ] `river.css` seems to work, but has an ugly TODO note about confirming with Timepoof? check the CSS doesn't override itself (as per "overlaps with monochrome") but then remove the warning
- [ ] "don't hard code sandbox board_id" in models/board.rb, try to trigger relevant callbacks when moving and make it clearer in the model near any after_destroy notes that they need to be wary around move_posts_to_sandbox
- [ ] drop marked_* in models/message.rb (see #419)
- [ ] "consolidate view code" in models/report.rb
- [ ] paginate board sections in presenter/board_presenter.rb? see about how the ordering API should deal with large continuities (paginate?)
- [ ] characters#search aliases, setting, facecast (#77 some waiting on #110 and #34)
- [ ] EPub downloader? (#9)
- [ ] Post notifications (#6), and in fact just a whole proper notifications system (#422)
